### ISSUE TITLE
[Bug] - *Update Documentation for Tracing Exporter / Jaeger-Exporter should be depricated* 

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [inspectIT/inspectit-ocelot-eum-server#34]
**Describe the bug**
Update Documentation to show/use OTLP Exporter.
Jaeger could receive OTLP-Exports and Jaeger-Exporter is depricated by Opentelemetry-Project. Would be removed at the next releases.

**Comment by EddeCCC** [comment]
Will be added in https://github.com/inspectIT/inspectit-ocelot-eum-server/pull/53

**Comment by EddeCCC** [comment]
Documentation was updated and merged in: https://github.com/inspectIT/inspectit-ocelot-eum-server/commit/cf78ac6375bb24dbde734d021d1886722fcf2c5c
